services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    env_file:
      - .env
      - example.env
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    environment:
      APP_ENV: ${APP_ENV:-local}
      PORT: ${PORT:-8080}
      BLUEPRINT_DB_URL: ${BLUEPRINT_DB_URL:-./db/data.db}
    volumes:
      - sqlite_bp:/app/db
volumes:
  sqlite_bp:
