services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .env
      - example.env
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      APP_ENV: ${APP_ENV:-local}
      PORT: ${PORT:-8080}
      BLUEPRINT_DB_URL: ${BLUEPRINT_DB_URL:-./db/data.db}
    volumes:
      - sqlite_bp:/app/db
    networks:
      - web

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    profiles:
      - production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

volumes:
  sqlite_bp:
  caddy_data:
  caddy_config:

networks:
  web:
    driver: bridge
