// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

type Comment struct {
	ID        interface{} `json:"id"`
	PostID    int64       `json:"post_id"`
	UserID    int64       `json:"user_id"`
	Comment   string      `json:"comment"`
	CreatedAt interface{} `json:"created_at"`
}

type Post struct {
	ID        interface{} `json:"id"`
	UserID    int64       `json:"user_id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	CreatedAt interface{} `json:"created_at"`
}

type User struct {
	ID        interface{} `json:"id"`
	Username  string      `json:"username"`
	Email     string      `json:"email"`
	CreatedAt interface{} `json:"created_at"`
}
