// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package repository

import (
	"context"
)

const postsGetAll = `-- name: PostsGetAll :many
SELECT id, user_id, title, content, created_at from posts
`

func (q *Queries) PostsGetAll(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, postsGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
