// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	GetComments(ctx context.Context) ([]Comment, error)
	PostsGetAll(ctx context.Context) ([]Post, error)
	UsersCreate(ctx context.Context, arg UsersCreateParams) (User, error)
	UsersGetAll(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
